export const assets = {
  icon: {
    logo: require('~/assets/icons/logo.png'),   
    star_white:require('~/assets/icons/trigger/star-white.png'),
    star_blue:require('~/assets/icons/trigger/star-white.png'),
    truck:require('~/assets/icons/different/truck.png'),
    verify:require('~/assets/icons/different/verify.png'),
    shopping:require('~/assets/icons/shopping-cart.png'),
    shopping_blue:require('~/assets/icons/shopping-cart-blue.png'),
    user:require('~/assets/icons/user.png'),
    sms: require('~/assets/icons/sms.png'),
    key:require('~/assets/icons/key.png'),

    //button
    bag:require('~/assets/icons/button/bag.png'),
    plus:require('~/assets/icons/trigger/plus.png'),
    minus:require('~/assets/icons/trigger/minus.png'),
    add:require('~/assets/icons/button/add.png'),
    trash:require('~/assets/icons/trash.png'),
    search : require('~/assets/icons/button/search-normal.png'),
    google: require('~/assets/icons/google.png'),
    facebook: require('~/assets/icons/facebook.png'),
    menu:require('~/assets/icons/button/menu.png'),
    login:require('~/assets/icons/button/login.png'),
    logout:require('~/assets/icons/button/logout.png'),
    //trigger
    close_circle_disabled: require('~/assets/icons/button/close-circle-disable.png'),
    close_circle_inactive: require('~/assets/icons/button/close-circle-inactive.png'),
    close_circle_focus: require('~/assets/icons/button/close-circle-focus.png'),
    close_circle_error: require('~/assets/icons/button/close-circle-error.png'),
    close_square: require('~/assets/icons/button/close-square.png'),
    eye_open: require('~/assets/icons/trigger/eye-open.png'),
    eye_slash: require('~/assets/icons/trigger/eye-slash.png'),
    checkBook :require('~/assets/icons/trigger/check-box-true.png'),
    unCheckBook :require('~/assets/icons/trigger/check-box-false.png'),
    switch_true:require('~/assets/icons/trigger/switch-true.png/'),
    switch_false:require('~/assets/icons/trigger/switch-false.png/'),
    radio_true:require('~/assets/icons/trigger/radio-true.png'),
    radio_false:require('~/assets/icons/trigger/radio-false.png'),
    like_true:require('~/assets/icons/trigger/like-true.png'),
    dislike_true:require('~/assets/icons/trigger/dislike-true.png'),
    like_false:require('~/assets/icons/trigger/like-false.png'),
    dislike_false:require('~/assets/icons/trigger/dislike-false.png'),
    send_bold:require('~/assets/icons/trigger/send-bold.png'),
    send_outline:require('~/assets/icons/trigger/send-outline.png'),
    //arrow
    arrow_right_white:require('~/assets/icons/arrows/arrow-right-white.png'),
    arrow_right_sm:require('~/assets/icons/arrows/arrow-right-sm.png'),
    arrowBack : require('~/assets/icons/arrows/arrow-left.png'),
    arrowDown: require('~/assets/icons/arrows/arrow-down-black.png'),
    arrowDownWhite: require('~/assets/icons/arrows/arrow-down-white.png'),
    arrowDownBlue:require('~/assets/icons/arrows/arrow-down-blue.png'),
    arrowUp : require('~/assets/icons/arrows/arrow-up.png'),
    arrowUpBlue : require('~/assets/icons/arrows/arrow-up-blue.png'),
 //footer
    footer_user_white:require('~/assets/icons/footer/footer-user-white.png'),
    footer_chat : require('~/assets/icons/footer/footer-chat.png'),
    footer_arrow_down : require('~/assets/icons/footer/footer-arrow-down.png'),
    footer_arrow_up : require('~/assets/icons/footer/footer-arrow-up.png'),
  },
 

  image:{
    product_demo:require('~/assets/images/product-demo.png'),
    banner_demo:require('~/assets/images/banner-demo.png'),
  }
}